[package]
name = "medic"
version = "0.2.8"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
rpassword = "2.0.0"
keepass = "0.4.4"
sha1 = "0.6.0"
indicatif = "0.11.0"
zxcvbn = "1.0.0"
csv = "1"
structopt = "0.2"
